#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    streams:
#      application-id: kafka-streams-app-43343
#      bootstrap-servers: localhost:9092
#      properties:
#        commit.interval.ms: 10
#        state.dir: /tmp/kafka-streams
#        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde


#logging:
#  level:
#    org.apache.kafka: DEBUG
#    org.apache.kafka.streams: DEBUG


#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: my-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


